image:
    - Visual Studio 2015
environment:
    matrix:
        - PYTHON: "C:\\Python27"
        - PYTHON: "C:\\Python34"
        - PYTHON: "C:\\Python35"
        - PYTHON: "C:\\Python36"
        - PYTHON: "C:\\Python27-x64"
        - PYTHON: "C:\\Python34-x64"
        - PYTHON: "C:\\Python35-x64"
        - PYTHON: "C:\\Python36-x64"
install:
    - "%PYTHON%\\python.exe -m pip install --upgrade setuptools pip"
    - "%PYTHON%\\python.exe -m pip install --upgrade virtualenv"
    - "%PYTHON%\\python.exe -m pip --version"
    - "%PYTHON%\\python.exe -m virtualenv --version"
    - "git --version"
    - "%PYTHON%\\python.exe -m pip install --upgrade flake8 pylint codecov"
    - "%PYTHON%\\python.exe -m pip install --upgrade pytest-flake8 pytest-pylint pytest-cov"
build: off
test_script:
    - "%PYTHON%\\python.exe -m pytest"
on_success:
    - "%PYTHON%\\python.exe -m codecov -X gcov"
skip_branch_with_pr: true
