image:
  - Visual Studio 2017
environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"
install:
  - "%PYTHON%\\python.exe -m pip install --upgrade setuptools pip"
  - "git --version"
  - "hg --version"
  - "%PYTHON%\\python.exe -m pip install --upgrade \"flake8==3.5.0\" \"pylint==1.8.4\" \"codecov==2.0.15\""
  - "%PYTHON%\\python.exe -m pip install --upgrade \"pytest-flake8==1.0.1\" \"pytest-pylint==0.9.0\""
  - "%PYTHON%\\python.exe -m pip install --upgrade \"pytest-cov==2.5.1\""
  - "choco install codecov"
build: off
test_script:
  - "%PYTHON%\\python.exe -m pytest --cov-report xml"
on_success:
  - "codecov -f coverage.xml"
skip_branch_with_pr: true
